using Android.App;
using Android.Content;
using Android.OS;
using Android.Util;
using AndroidX.Core.App;

namespace AppTemplate.Droid;

/// <summary>
/// Receives an <see cref="AlarmManager"/> alarm and posts the corresponding notification.
/// </summary>
/// <remarks>
/// This receiver is the target of the <see cref="PendingIntent"/> registered when a notification
/// is scheduled. It is not exported because only the app itself (and the OS delivering the alarm)
/// should be able to trigger it.
/// </remarks>
[BroadcastReceiver(Enabled = true, Exported = false)]
public class NotificationAlarmReceiver : BroadcastReceiver
{
    private const string LogTag = nameof(NotificationAlarmReceiver);

    /// <summary>The notification channel used for scheduled notifications.</summary>
    public const string ChannelId = "scheduled_notifications";

    /// <summary>Intent extra carrying the unique notification id.</summary>
    public const string ExtraNotificationId = "notification_id";

    /// <summary>Intent extra carrying the notification title.</summary>
    public const string ExtraTitle = "notification_title";

    /// <summary>Intent extra carrying the notification message body.</summary>
    public const string ExtraMessage = "notification_message";

    public override void OnReceive(Context? context, Intent? intent)
    {
        if (context is null || intent is null)
        {
            return;
        }

        Log.Info(LogTag, "Alarm received; posting scheduled notification.");

        try
        {
            PostNotification(context, intent);
        }
        catch (Exception ex)
        {
            Log.Error(LogTag, $"Failed to post scheduled notification: {ex}");
        }
    }

    private static void PostNotification(Context context, Intent intent)
    {
        var notificationManager = (NotificationManager?)context.GetSystemService(Context.NotificationService);
        if (notificationManager is null)
        {
            Log.Warn(LogTag, "NotificationManager is unavailable; cannot post notification.");
            return;
        }

        EnsureChannel(notificationManager);

        // TODO: Replace this placeholder content with the real notification payload that was
        // persisted by the app's scheduled-notification service. The id/title/message are read
        // from the intent extras populated when the alarm was scheduled.
        var notificationId = intent.GetIntExtra(ExtraNotificationId, 0);
        var title = intent.GetStringExtra(ExtraTitle) ?? "Scheduled notification";
        var message = intent.GetStringExtra(ExtraMessage) ?? "You have a scheduled reminder.";

        // TODO: Swap the placeholder system icon for the app's own notification icon
        // (e.g. Resource.Mipmap.icon, generated by the Uno SDK during the Android build).
        var notification = new NotificationCompat.Builder(context, ChannelId)
            .SetContentTitle(title)
            .SetContentText(message)
            .SetSmallIcon(Android.Resource.Drawable.IcDialogInfo)
            .SetAutoCancel(true)
            .SetPriority((int)NotificationPriority.Default)
            .Build();

        notificationManager.Notify(notificationId, notification);
    }

    /// <summary>
    /// Creates the notification channel required on Android 8.0 (API 26)+ before any notification
    /// can be posted. The call is a no-op if the channel already exists.
    /// </summary>
    private static void EnsureChannel(NotificationManager notificationManager)
    {
        if (Build.VERSION.SdkInt < BuildVersionCodes.O)
        {
            return;
        }

        // TODO: Localize the channel name/description and tune importance to match the app's
        // scheduled-notification requirements.
        var channel = new NotificationChannel(
            ChannelId,
            "Scheduled notifications",
            NotificationImportance.Default)
        {
            Description = "Notifications scheduled by the app.",
        };

        notificationManager.CreateNotificationChannel(channel);
    }
}
