using Android.App;
using Android.Content;
using Android.OS;
using Android.Util;
using AndroidX.Core.App;

namespace AppTemplate.Droid;

/// <summary>
/// Minimal payload describing a notification to (re-)schedule. Replace this with the app's own
/// persisted model, or map onto it - it is intentionally tiny so the receivers compile and work
/// without dragging in an app-specific data model.
/// </summary>
/// <param name="Id">
/// Stable identifier used both as the notification id and the <see cref="PendingIntent"/> request
/// code. It must stay the same across process restarts so a reboot rebuilds the same alarms.
/// </param>
/// <param name="Title">Notification title.</param>
/// <param name="Message">Notification body text.</param>
/// <param name="TriggerTimeUtc">UTC instant at which the notification should fire.</param>
public record ScheduledNotification(int Id, string Title, string Message, DateTimeOffset TriggerTimeUtc);

/// <summary>
/// Receives an <see cref="AlarmManager"/> alarm and posts the corresponding notification.
/// </summary>
/// <remarks>
/// This receiver is the target of the <see cref="PendingIntent"/> registered when a notification
/// is scheduled. It is not exported because only the app itself (and the OS delivering the alarm)
/// should be able to trigger it.
/// </remarks>
[BroadcastReceiver(Enabled = true, Exported = false)]
public class NotificationAlarmReceiver : BroadcastReceiver
{
    // Hard-coded (not nameof(NotificationAlarmReceiver), which is 25 chars): android.util.Log
    // enforces a 23-character tag limit on API < 26 and throws if it's exceeded.
    private const string LogTag = "NotifAlarmReceiver";

    /// <summary>The notification channel used for scheduled notifications.</summary>
    public const string ChannelId = "scheduled_notifications";

    /// <summary>Intent extra carrying the unique notification id.</summary>
    public const string ExtraNotificationId = "notification_id";

    /// <summary>Intent extra carrying the notification title.</summary>
    public const string ExtraTitle = "notification_title";

    /// <summary>Intent extra carrying the notification message body.</summary>
    public const string ExtraMessage = "notification_message";

    public override void OnReceive(Context? context, Intent? intent)
    {
        if (context is null || intent is null)
        {
            return;
        }

        Log.Info(LogTag, "Alarm received; posting scheduled notification.");

        try
        {
            PostNotification(context, intent);
        }
        catch (Exception ex)
        {
            Log.Error(LogTag, $"Failed to post scheduled notification: {ex}");
        }
    }

    private static void PostNotification(Context context, Intent intent)
    {
        var notificationId = intent.GetIntExtra(ExtraNotificationId, -1);
        if (notificationId < 0)
        {
            // No/invalid id extra: bail rather than fall back to a shared id that would make
            // unrelated notifications overwrite each other and hide a wiring bug.
            Log.Warn(LogTag, $"Missing or invalid {ExtraNotificationId} extra; dropping notification.");
            return;
        }

        EnsureChannel(context);

        // TODO: Replace these fallbacks with the real persisted payload. The id/title/message are
        // read from the intent extras populated when the alarm was scheduled.
        var title = intent.GetStringExtra(ExtraTitle) ?? "Scheduled notification";
        var message = intent.GetStringExtra(ExtraMessage) ?? "You have a scheduled reminder.";

        // Tap intent: bring the app to the foreground when the notification is tapped. Forward the
        // notification id so the app can deep-link to the relevant content if it wants to.
        var tapIntent = new Intent(context, typeof(MainActivity));
        tapIntent.SetAction(Intent.ActionView);
        tapIntent.PutExtra(ExtraNotificationId, notificationId);
        tapIntent.AddFlags(ActivityFlags.ClearTop | ActivityFlags.SingleTop);

        var tapPendingIntent = PendingIntent.GetActivity(
            context,
            notificationId,
            tapIntent,
            PendingIntentFlags.UpdateCurrent | PendingIntentFlags.Immutable);

        // TODO: Swap the placeholder system icon for the app's own notification icon
        // (e.g. Resource.Mipmap.icon_foreground, generated by the Uno SDK during the Android build).
        var notification = new NotificationCompat.Builder(context, ChannelId)
            .SetContentTitle(title)
            .SetContentText(message)
            .SetSmallIcon(Android.Resource.Drawable.IcDialogInfo)
            .SetAutoCancel(true)
            .SetCategory(NotificationCompat.CategoryReminder)
            .SetContentIntent(tapPendingIntent)
            .SetPriority(NotificationCompat.PriorityDefault)
            .Build();

        var notificationManager = NotificationManagerCompat.From(context);
        try
        {
            notificationManager.Notify(notificationId, notification);
        }
        catch (Java.Lang.SecurityException)
        {
            // POST_NOTIFICATIONS is not granted (runtime permission on Android 13 / API 33+).
            // The app should request it before scheduling notifications.
            Log.Warn(LogTag, "POST_NOTIFICATIONS not granted; notification was not posted.");
        }
    }

    /// <summary>
    /// Creates the notification channel required on Android 8.0 (API 26)+ before any notification
    /// can be posted. The call is a no-op if the channel already exists.
    /// </summary>
    private static void EnsureChannel(Context context)
    {
        if (Build.VERSION.SdkInt < BuildVersionCodes.O)
        {
            return;
        }

        var notificationManager = (NotificationManager?)context.GetSystemService(Context.NotificationService);
        if (notificationManager is null)
        {
            return;
        }

        // TODO: Localize the channel name/description and tune importance to match the app's
        // scheduled-notification requirements.
        var channel = new NotificationChannel(
            ChannelId,
            "Scheduled notifications",
            NotificationImportance.Default)
        {
            Description = "Notifications scheduled by the app.",
        };

        notificationManager.CreateNotificationChannel(channel);
    }
}
