name: Bug Report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what did you expect instead?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the bug.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App version
      description: Version of the app where the bug occurs.
      placeholder: e.g. 1.2.0

  - type: dropdown
    id: platforms
    attributes:
      label: Platform(s)
      description: Which platform(s) are affected?
      multiple: true
      options:
        - All platforms
        - WebAssembly
        - Android
        - iOS
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Logs, screenshots, or any other relevant information.
