name: Feature Request
description: Suggest a new capability
labels: [feature-request]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: What new capability would you like to see?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case / motivation
      description: Why is this feature needed? What problem does it solve?
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App version
      description: Version of the app you are using.
      placeholder: e.g. 1.2.0

  - type: dropdown
    id: platforms
    attributes:
      label: Relevant platform(s)
      description: Which platform(s) should this feature target?
      multiple: true
      options:
        - All platforms
        - WebAssembly
        - Android
        - iOS
        - macOS
        - Windows
        - Linux

  - type: dropdown
    id: renderer
    attributes:
      label: Renderer
      description: Which renderer is this relevant to? Your app uses Skia if you find `SkiaRenderer` in the `.csproj` project file.
      multiple: true
      options:
        - All renderers
        - Skia
        - Native

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other information, mockups, or references.
