global using System.Collections.Immutable;
global using AppTemplate.Models;
global using AppTemplate.Core.Services;
global using AppTemplate.Converters;
global using AppTemplate.Services.Dialogs;
global using AppTemplate.Services.Localization;
global using AppTemplate.Services.Settings;
global using AppTemplate.Services.Theming;
global using AppTemplate.Shell;
global using AppTemplate.ViewModels;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
